
INSERT INTO CAPSTONE (ID, ADDITIONAL_DRIVERS, ADDRESS1, ADDRESS2, CAR_TYPE, CITY, COMMERCIAL_PURPOSES, DATE_REGISTERED, ENGINE_SIZE, FIRST_NAME, LAST_NAME, OUTSIDE_STATE, POST_CODE, PREFIX , TEL_NUMBER, VEHICLE_VALUE, QUOTE)
VALUES (1, 1, '123', 'something road', 'Cabriolet', 'Belfast', 'No', '11-05-97', '1000', 'Robyn', 'Thompson', 'No', 'BT148LJ', 'Miss', '1234', '50000', '500');
